image: node:16.15-alpine3.16

pages:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - echo start building
    - npm install
    - npm run docs:build
  artifacts:
    paths:
      - public
  only:
    - dev
