image: node:16.20-alpine3.17

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn install
    - yarn docs:build

pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir public && cp -rf docs/src/.vuepress/dist/* public


  artifacts:
    paths:
    - public
    - docs/src/.vuepress/dist
only:
  - dev
