pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir public && cp -rf docs/src/.vuepress/dist/* public
  artifacts:
    paths:
    - public
  only:
    - dev

cache:
  paths:
    - node_modules
    - docs/src/.vuepress/dist
