image: node:16-alpine

pages:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - apk add --no-cache git
    - yarn install
    - npm run docs:build
  artifacts:
    paths:
      - public
  only:
    - main
